[server]
headless = true
port = 8501
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#070a13"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
font = "sans serif"
